import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-base-200">
          <div className="navbar bg-base-100">
            <div className="flex-1 px-2 font-semibold">
              <Link href="/">Work</Link>
              <Link className="btn btn-ghost btn-sm" href="/monsters">
                About
              </Link>
              <Link className="btn btn-ghost btn-sm" href="/monsters">
                Contact
              </Link>
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
